import time
print("multiple times print1")
time.sleep(1)
print("multiple times print2")
time.sleep(1)
print("multiple times print3")
time.sleep(1)
print("multiple times print4")
time.sleep(1)
print("multiple times print5")
time.sleep(1)
print("multiple times print6")